
[functions.phone-change-request]
enabled = true
verify_jwt = true
import_map = "./functions/phone-change-request/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/phone-change-request/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/phone-change-request/*.html" ]

[functions.send-event-reminders]
enabled = true
verify_jwt = false
entrypoint = "./functions/send-event-reminders/index.ts"
